/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    DefenseBoardDrawer: typeof import('./components/DefenseBoardDrawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoDrawer: typeof import('./components/InfoDrawer.vue')['default']
    OfficeDrawer: typeof import('./components/OfficeDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentDrawer: typeof import('./components/StudentDrawer.vue')['default']
    TeacherDrawer: typeof import('./components/TeacherDrawer.vue')['default']
    UserInfoBar: typeof import('./components/UserInfoBar.vue')['default']
  }
}
